version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: no
    ports:
      - 5400:5400
    networks:
      - ts-network
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port 5400 --debug
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - ts-network

networks:
  ts-network:
    driver: bridge